-- RiskLab: banco e funções para Supabase gratuito
-- Execute este arquivo inteiro no SQL Editor de um projeto NOVO.

create extension if not exists pgcrypto;

create table if not exists public.rooms (
  id bigint generated by default as identity primary key,
  code text unique not null,
  title text not null,
  facilitator_pin_hash text not null,
  active_activity bigint,
  phase text not null default 'individual' check (phase in ('individual','group','results','vote')),
  created_at timestamptz not null default now()
);
create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  name text not null,
  token text not null,
  created_at timestamptz not null default now(),
  unique(room_id,token)
);
create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null,
  group_id bigint not null references public.groups(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique(auth_user_id,group_id)
);
create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete cascade,
  module text not null,
  title text not null,
  instructions text not null,
  activity_type text not null,
  config jsonb not null default '{}'::jsonb,
  status text not null default 'draft',
  duration integer not null default 10,
  created_at timestamptz not null default now()
);
alter table public.rooms drop constraint if exists rooms_active_activity_fkey;
alter table public.rooms add constraint rooms_active_activity_fkey foreign key(active_activity) references public.activities(id) on delete set null;
create table if not exists public.individual_responses (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  participant_id bigint not null references public.participants(id) on delete cascade,
  answer text not null default '',
  confidence integer not null default 0 check(confidence between 0 and 100),
  rationale text not null default '',
  submitted_at timestamptz not null default now(),
  unique(activity_id,participant_id)
);
create table if not exists public.group_syntheses (
  id bigint generated by default as identity primary key,
  activity_id bigint not null references public.activities(id) on delete cascade,
  group_id bigint not null references public.groups(id) on delete cascade,
  decision text not null default '', rationale text not null default '', dissent text not null default '', review_trigger text not null default '',
  submitted_at timestamptz not null default now(), unique(activity_id,group_id)
);
create table if not exists public.facilitator_access (
  room_id bigint not null references public.rooms(id) on delete cascade,
  auth_user_id uuid not null,
  granted_at timestamptz not null default now(),
  primary key(room_id,auth_user_id)
);

alter table public.rooms enable row level security;
alter table public.groups enable row level security;
alter table public.participants enable row level security;
alter table public.activities enable row level security;
alter table public.individual_responses enable row level security;
alter table public.group_syntheses enable row level security;
alter table public.facilitator_access enable row level security;
-- O acesso do navegador ocorre somente pelas funções RPC abaixo.

create or replace function public.is_facilitator(p_room_id bigint)
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from facilitator_access where room_id=p_room_id and auth_user_id=auth.uid());
$$;

create or replace function public.risklab_facilitator_login(p_room_code text,p_pin text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r rooms;
begin
  select * into r from rooms where upper(code)=upper(trim(p_room_code));
  if r.id is null or crypt(p_pin,r.facilitator_pin_hash)<>r.facilitator_pin_hash then
    return jsonb_build_object('ok',false,'message','Código da sala ou senha inválidos.');
  end if;
  insert into facilitator_access(room_id,auth_user_id) values(r.id,auth.uid()) on conflict do nothing;
  return jsonb_build_object('ok',true,'room_id',r.id);
end $$;

create or replace function public.risklab_join_participant(p_room_code text,p_group_token text,p_name text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare g groups; pid bigint; rid bigint;
begin
  if auth.uid() is null then return jsonb_build_object('ok',false,'message','Sessão anônima não iniciada.'); end if;
  select gg.*,rr.id into g,rid from groups gg join rooms rr on rr.id=gg.room_id where upper(rr.code)=upper(trim(p_room_code)) and upper(gg.token)=upper(trim(p_group_token));
  if g.id is null or length(trim(p_name))<2 then return jsonb_build_object('ok',false,'message','Sala, grupo ou nome inválido.'); end if;
  insert into participants(auth_user_id,group_id,name) values(auth.uid(),g.id,left(trim(p_name),80))
  on conflict(auth_user_id,group_id) do update set name=excluded.name returning id into pid;
  return jsonb_build_object('ok',true,'room_id',g.room_id,'group_id',g.id,'participant_id',pid);
end $$;

create or replace function public.risklab_facilitator_dashboard(p_room_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare r rooms; a activities; result jsonb; totalp int; done int;
begin
  if not is_facilitator(p_room_id) then return jsonb_build_object('ok',false); end if;
  select * into r from rooms where id=p_room_id;
  if r.active_activity is not null then select * into a from activities where id=r.active_activity; end if;
  select count(*) into totalp from participants p join groups g on g.id=p.group_id where g.room_id=p_room_id;
  if a.id is not null then select count(*) into done from individual_responses where activity_id=a.id; else done:=0; end if;
  result:=jsonb_build_object('ok',true,'room',to_jsonb(r),'active',case when a.id is null then null else to_jsonb(a) end,
    'activities',(select coalesce(jsonb_agg(to_jsonb(x) order by x.id),'[]'::jsonb) from activities x where x.room_id=p_room_id),
    'groups',(select coalesce(jsonb_agg(to_jsonb(x) order by x.id),'[]'::jsonb) from groups x where x.room_id=p_room_id),
    'total_participants',totalp,'individual_done',done,
    'stats',(select coalesce(jsonb_agg(jsonb_build_object('id',g.id,'name',g.name,'participants',(select count(*) from participants p where p.group_id=g.id),'responses',(select count(*) from individual_responses ir join participants p on p.id=ir.participant_id where ir.activity_id=a.id and p.group_id=g.id),'synthesis',(select to_jsonb(s) from group_syntheses s where s.activity_id=a.id and s.group_id=g.id)) order by g.id),'[]'::jsonb) from groups g where g.room_id=p_room_id));
  return result;
end $$;

create or replace function public.risklab_activate_activity(p_room_id bigint,p_activity_id bigint)
returns void language plpgsql security definer set search_path=public as $$ begin
 if not is_facilitator(p_room_id) then raise exception 'não autorizado'; end if;
 update activities set status='closed' where room_id=p_room_id; update activities set status='active' where id=p_activity_id and room_id=p_room_id;
 update rooms set active_activity=p_activity_id,phase='individual' where id=p_room_id;
end $$;
create or replace function public.risklab_set_phase(p_room_id bigint,p_phase text)
returns void language plpgsql security definer set search_path=public as $$ begin
 if not is_facilitator(p_room_id) then raise exception 'não autorizado'; end if;
 if p_phase not in ('individual','group','results','vote') then raise exception 'fase inválida'; end if;
 update rooms set phase=p_phase where id=p_room_id;
end $$;
create or replace function public.risklab_close_activity(p_room_id bigint)
returns void language plpgsql security definer set search_path=public as $$ begin
 if not is_facilitator(p_room_id) then raise exception 'não autorizado'; end if;
 update activities set status='closed' where id=(select active_activity from rooms where id=p_room_id); update rooms set active_activity=null,phase='individual' where id=p_room_id;
end $$;
create or replace function public.risklab_reset_room(p_room_id bigint)
returns void language plpgsql security definer set search_path=public as $$ begin
 if not is_facilitator(p_room_id) then raise exception 'não autorizado'; end if;
 delete from individual_responses where activity_id in(select id from activities where room_id=p_room_id);
 delete from group_syntheses where activity_id in(select id from activities where room_id=p_room_id);
 update activities set status='draft' where room_id=p_room_id; update rooms set active_activity=null,phase='individual' where id=p_room_id;
end $$;

create or replace function public.risklab_participant_status(p_participant_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare p participants; g groups; r rooms; a activities; syn group_syntheses;
begin
 select * into p from participants where id=p_participant_id and auth_user_id=auth.uid(); if p.id is null then return jsonb_build_object('ok',false); end if;
 select * into g from groups where id=p.group_id; select * into r from rooms where id=g.room_id;
 if r.active_activity is not null then select * into a from activities where id=r.active_activity; select * into syn from group_syntheses where activity_id=a.id and group_id=g.id; end if;
 return jsonb_build_object('ok',true,'participant',to_jsonb(p),'group',to_jsonb(g),'room',to_jsonb(r),'activity',case when a.id is null then null else to_jsonb(a) end,
 'group_members',case when a.id is null then '[]'::jsonb else (select coalesce(jsonb_agg(jsonb_build_object('name',pp.name,'answer',ir.answer,'confidence',ir.confidence,'rationale',ir.rationale) order by pp.name),'[]'::jsonb) from participants pp left join individual_responses ir on ir.participant_id=pp.id and ir.activity_id=a.id where pp.group_id=g.id) end,
 'group_synthesis',case when syn.id is null then null else to_jsonb(syn) end);
end $$;

create or replace function public.risklab_save_individual(p_participant_id bigint,p_activity_id bigint,p_answer text,p_confidence integer,p_rationale text)
returns void language plpgsql security definer set search_path=public as $$ begin
 if not exists(select 1 from participants where id=p_participant_id and auth_user_id=auth.uid()) then raise exception 'não autorizado'; end if;
 insert into individual_responses(activity_id,participant_id,answer,confidence,rationale) values(p_activity_id,p_participant_id,left(coalesce(p_answer,''),8000),greatest(0,least(100,coalesce(p_confidence,0))),left(coalesce(p_rationale,''),8000))
 on conflict(activity_id,participant_id) do update set answer=excluded.answer,confidence=excluded.confidence,rationale=excluded.rationale,submitted_at=now();
end $$;
create or replace function public.risklab_save_group(p_participant_id bigint,p_activity_id bigint,p_decision text,p_rationale text,p_dissent text,p_review_trigger text)
returns void language plpgsql security definer set search_path=public as $$ declare gid bigint; begin
 select group_id into gid from participants where id=p_participant_id and auth_user_id=auth.uid(); if gid is null then raise exception 'não autorizado'; end if;
 insert into group_syntheses(activity_id,group_id,decision,rationale,dissent,review_trigger) values(p_activity_id,gid,left(coalesce(p_decision,''),8000),left(coalesce(p_rationale,''),8000),left(coalesce(p_dissent,''),8000),left(coalesce(p_review_trigger,''),8000))
 on conflict(activity_id,group_id) do update set decision=excluded.decision,rationale=excluded.rationale,dissent=excluded.dissent,review_trigger=excluded.review_trigger,submitted_at=now();
end $$;

create or replace function public.risklab_export_active(p_room_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$ declare aid bigint; begin
 if not is_facilitator(p_room_id) then raise exception 'não autorizado'; end if; select active_activity into aid from rooms where id=p_room_id;
 return jsonb_build_object('individual',(select coalesce(jsonb_agg(jsonb_build_object('grupo',g.name,'participante',p.name,'answer',ir.answer,'confidence',ir.confidence,'rationale',ir.rationale,'submitted_at',ir.submitted_at) order by g.name,p.name),'[]'::jsonb) from individual_responses ir join participants p on p.id=ir.participant_id join groups g on g.id=p.group_id where ir.activity_id=aid),
 'syntheses',(select coalesce(jsonb_agg(jsonb_build_object('grupo',g.name,'decision',s.decision,'rationale',s.rationale,'dissent',s.dissent,'review_trigger',s.review_trigger,'submitted_at',s.submitted_at) order by g.name),'[]'::jsonb) from group_syntheses s join groups g on g.id=s.group_id where s.activity_id=aid));
end $$;

revoke all on all tables in schema public from anon,authenticated;
grant usage on schema public to anon,authenticated;
grant execute on function public.risklab_facilitator_login(text,text) to authenticated;
grant execute on function public.risklab_join_participant(text,text,text) to authenticated;
grant execute on function public.risklab_facilitator_dashboard(bigint) to authenticated;
grant execute on function public.risklab_activate_activity(bigint,bigint) to authenticated;
grant execute on function public.risklab_set_phase(bigint,text) to authenticated;
grant execute on function public.risklab_close_activity(bigint) to authenticated;
grant execute on function public.risklab_reset_room(bigint) to authenticated;
grant execute on function public.risklab_participant_status(bigint) to authenticated;
grant execute on function public.risklab_save_individual(bigint,bigint,text,integer,text) to authenticated;
grant execute on function public.risklab_save_group(bigint,bigint,text,text,text,text) to authenticated;
grant execute on function public.risklab_export_active(bigint) to authenticated;

-- Dados iniciais
insert into rooms(code,title,facilitator_pin_hash)
values('RISCO8H','Vieses Cognitivos e Armadilhas Analíticas',crypt('RISKLAB2026',gen_salt('bf')))
on conflict(code) do nothing;

do $$ declare rid bigint; begin
 select id into rid from rooms where code='RISCO8H';
 insert into groups(room_id,name,token) values
 (rid,'Grupo 1','GRUPO1'),(rid,'Grupo 2','GRUPO2'),(rid,'Grupo 3','GRUPO3'),(rid,'Grupo 4','GRUPO4') on conflict do nothing;
 if not exists(select 1 from activities where room_id=rid) then
 insert into activities(room_id,module,title,instructions,activity_type,config,duration) values
 (rid,'Abertura','Você investiria?','Analise o caso com informação incompleta. Escolha aprovar, rejeitar ou pedir mais informações. Depois indique sua confiança e justificativa.','choice','{"options":["Aprovar","Rejeitar","Pedir mais informações"],"group_phase":true}',12),
 (rid,'Fundamentos','Bastão e bola','Um bastão e uma bola custam R$ 1,10. O bastão custa R$ 1,00 a mais que a bola. Quanto custa a bola?','quiz','{"options":["R$ 0,05","R$ 0,10","R$ 0,15","R$ 0,20"],"correct":"R$ 0,05"}',5),
 (rid,'Fundamentos','Problema de Linda','Leia o perfil apresentado pelo facilitador e escolha a alternativa mais provável. Registre também sua confiança.','choice','{"options":["Linda é bancária","Linda é bancária e ativista feminista"]}',6),
 (rid,'Fundamentos','Radar executivo','Classifique cada decisão como predominantemente intuitiva ou analítica e indique quando seria necessário desacelerar.','matrix','{"items":["Bloquear uma transação suspeita","Aprovar nova política de crédito","Responder a incidente cibernético","Recalibrar modelo de risco","Definir apetite a risco"]}',15),
 (rid,'Vieses','Viés de confirmação','Avalie as evidências recebidas e indique se sustentam, contradizem ou são inconclusivas em relação à hipótese inicial.','evidence','{"options":["Sustenta","Contradiz","Inconclusiva"]}',15),
 (rid,'Vieses','Excesso de confiança','Para cada pergunta, informe um intervalo mínimo e máximo que você acredita conter a resposta correta.','intervals','{"items":["População do Canadá (milhões)","Extensão do rio Amazonas (km)","Número de países membros da ONU","Ano de fundação do Banco do Brasil"]}',12),
 (rid,'Vieses','Teste de ancoragem','Estime o percentual de perdas operacionais no cenário. Registre o valor e explique quais informações influenciaram sua estimativa.','number','{"min":0,"max":100,"unit":"%"}',10),
 (rid,'Vieses','Disponibilidade','Ordene os riscos do mais provável para o menos provável e explique se notícias recentes influenciaram sua percepção.','ranking','{"items":["Ataque cibernético","Fraude interna","Erro operacional","Falha de fornecedor","Evento climático extremo"]}',12),
 (rid,'Vieses','Viés retrospectivo','Antes de conhecer o desfecho, estime a probabilidade do evento. Após a revelação, registre o que parecia previsível apenas em retrospecto.','before_after','{}',12),
 (rid,'Armadilhas analíticas','Caça às armadilhas do dashboard','Identifique problemas nos indicadores: médias que escondem extremos, bases incompletas, correlações enganosas, escalas inadequadas e metas mal definidas.','audit','{"categories":["Qualidade do dado","Visualização","Interpretação","Causalidade","Incentivos"]}',20),
 (rid,'Armadilhas analíticas','O modelo disse...','Compare a previsão do modelo com a informação qualitativa. Decida: seguir modelo, seguir especialista ou escalar para revisão.','choice','{"options":["Seguir o modelo","Seguir o especialista","Escalar para revisão"]}',15),
 (rid,'Casos reais','Diagnóstico de caso financeiro','Analise o caso atribuído ao grupo. Identifique vieses, falhas analíticas, incentivos, sinais ignorados e mecanismos de governança que poderiam reduzir o risco.','case','{"cases":["Lehman Brothers","Barings Bank","Silicon Valley Bank","Credit Suisse","Archegos"]}',25),
 (rid,'Encerramento','Comitê executivo de risco','Tome a decisão final para o cenário integrado. Apresente evidências, hipótese contrária, opinião minoritária e gatilho objetivo de revisão.','committee','{"group_phase":true,"peer_vote":true}',30);
 end if;
end $$;
